### ISSUE TITLE
withLinks : true causes large performance drop

### ISSUE THREAD

**Issue by brumar** [abodelot/jquery.json-viewer#11]
Hello, thanks a lot for your work. This is a very helpful library!

I work with large JSONs and `jsonViewer` takes few minutes to finishs its job. Yet, when I use the option `withLinks: False`, its blazingly fast.

I don't know if it's possible to use lighter regexps, but maybe the simplest way to go would be to use withLinks: False as a default option or just warn the users about this problem.

**Comment by abodelot** [comment]
Hi! Thank you for your feedback.

I couldn't observe a significative performance difference between `withLinks: true` and `withLinks: false`, even when parsing 1000+ urls.

Would you mind providing a JSON sample where you can reproduce such a difference?

Regardless of `withLinks` option usage, there is definitely a performance issue when working with large JSON objects. I'll see if I can speed-up HTML generation.

**Comment by abodelot** [comment]
Thanks to issue #13, I've been able to reproduce this issue. You were right, this is definitely related to the regexp used by `withLinks` option.

**Comment by brumar** [comment]
Hello, good news ! Sorry for having left without helping you more :/
