### ISSUE TITLE
Not working with list

### ISSUE THREAD

**Issue by ErShakirAnsari** [abodelot/jquery.json-viewer#13]
**Not working with below json:**

page becomes irresponsive 

```
{
   "randomUUID": [
      "91563848-3db7-47af-8dbb-825721e8907b",
      "826b23ce-2669-4122-981f-3e2e4429159d",
      "e32111a0-6a87-49ab-b58f-a01bf8d28ba0",
      "c055a894-698e-41c0-b85f-7510a7351d9d",
      "b1140fd3-018a-4af5-af4c-b24763335fac",
      "29ea7d0f-1c2b-4bf1-bbaa-e7bfac2d81bd",
      "6e244d8b-db62-4d50-a7fe-79c3d7bf5256"
   ],
   "serverTime": 1564555406117
}
```

**Comment by abodelot** [comment]
Hi,

Thank your for reporting this issue! It seems this is not related to links, but to UUID strings.

For a still unknown reason, the URL detection regexp is awfully slow with strings such as the ones featured in your example. I believe this is related to string length.

This is definitely related to issue #11.

In the mean time, I suggest you disable the withLink option (`{withLinks: false}`)
