### ISSUE TITLE
how to use jquery.json-viewer in react

### ISSUE THREAD

**Issue by mwb-27** [abodelot/jquery.json-viewer#15]
how to use  jquery.json-viewer in react.
import xx  from 'jquery.json-viewer'?

**Comment by abodelot** [comment]
Hi,

This jquery plugin is written ES5, there is no module or import system.

You must include the sources in your HTML document:

```html
<html>
  <head>
    ...
    <script src="json-viewer/jquery.json-viewer.js"></script>
    <link href="json-viewer/jquery.json-viewer.css" type="text/css" rel="stylesheet">
  </head>
```

You need to make sure jQuery is also included in your HTML document.

**Comment by seyfer** [comment]
Isn't it relatively easy to add some integration with module or import?

**Comment by seyfer** [comment]
@mwb-27 I made it connected to ES6 with webpack and scss in this way

js:
`import 'jquery.json-viewer/json-viewer/jquery.json-viewer';`
scss:
`@import "~jquery.json-viewer/json-viewer/jquery.json-viewer.css";`
