### ISSUE TITLE
collapsed ? 

### ISSUE THREAD

**Issue by umitsamli** [abodelot/jquery.json-viewer#18]
Hi,
Searching(ctrl+f) on the page does not work when using collapsed = true;
![image](https://user-images.githubusercontent.com/8467080/73256536-256c9780-41d3-11ea-961c-2adff973e02d.png)

after manuel open:
![image](https://user-images.githubusercontent.com/8467080/73256504-14238b00-41d3-11ea-9052-c460c6527dd1.png)

**Comment by abodelot** [comment]
Hi,

The Ctrl+F search is a browser feature, based on what's actually displayed in the HTML document, so you cannot make it match with hidden content.

However, you could write your own search function, that would walk recursively the given json object and match all keys and values against your input.
