### ISSUE TITLE
recommendation add another option keep quotation mark

### ISSUE THREAD

**Issue by he-yang** [abodelot/jquery.json-viewer#2]
the rendered json would be something like this

`{`
`a: 1`
`}`

but sometimes, users may need quotation mark for a.
`{`
`"a": 1`
`}`

it is recommended that you could add an option to keep those quotation marks.

**Comment by abodelot** [comment]
Hi, thank you for your interest.

I'll add an option for this.

**Comment by he-yang** [comment]
Thank you for your prompt response.
