### ISSUE TITLE
Ability to parse a string field as json

### ISSUE THREAD

**Issue by edokan** [abodelot/jquery.json-viewer#22]
My json has a field, it may contain a regular message or another json as string. It would be nice to have a feature that lets me to click that field, perform action as `Decode as json,` and string field becomes a property, and its contents are displayed a json too as if it was just another object property.

**Comment by abodelot** [comment]
Hi! Sorry but this seems to be out of scope.
I'd suggest to deserialize all the JSON content that you want to display before sending it to the `jsonViewer` function.
