### ISSUE TITLE
Hi CDN to jquery.json-viewer.js and jquery.json-viewer.css ..?¿

### ISSUE THREAD

**Issue by EOM** [abodelot/jquery.json-viewer#24]
Hi 
Exist CDN to  jquery.json-viewer.min.js and jquery.json-viewer.min.css ..?

**Comment by zepc007** [comment]
https://cdn.bootcdn.net/ajax/libs/jquery-jsonview/1.2.3/jquery.jsonview.min.css
https://cdn.bootcdn.net/ajax/libs/jquery-jsonview/1.2.3/jquery.jsonview.min.js
You're welcom.

**Comment by abodelot** [comment]
Hi, there isn't any CDN for jquery.json-viewer assets at the moment.

The links above are unavailable, and maybe not even related to this project.
